name: Build and Deploy to S3
on: [push]
jobs:
  build:
    name: Build, Lint, and Test project on Node ${{ matrix.node }} and ${{ matrix.os }}
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x'] # '16.x',
        os: [ubuntu-latest] # macOS-latest windows-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v3.2.0
        with:
          folder: dist
          bucket: ${{ secrets.AWS_BUCKET_PATH }} # uses bucket + /path
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          delete-removed: false
          no-cache: true
          private: false
